### ISSUE TITLE
Updating the PR by merging other branch does not seem to be detected 

### ISSUE THREAD

**Issue by qbbalys** [n7mobile/concourse-bitbucket-pr#1]
As in the title: when I merge a develop branch into the existing PR branch the resource does not yield a new version.

**Comment by antrov** [comment]
Indeed, sorting of versions by its IDs was leading to skipping of some PRs. 

Resolution: changed sorting key to the timestamp of a commit. 
Additionally, we simplified Version model. From now, it contains only full SHA1 of PR-ed commit.
