### ISSUE TITLE
[Question] Build not triggered when additional commits arrive in Pull Request

### ISSUE THREAD

**Issue by kardashov** [n7mobile/concourse-bitbucket-pr#3]
Hi. I've set up pipeline with PR resource in its simplest form. It checks BitBucket repo every 2 minutes.  When new PR arrives, Concourse build is triggered as expected and completes successfully.
Some time later I push additional commits to existing PR and expect it to trigger build again, but it does not happen.
Question: is it possible to trigger build again for newer commits? Thanks.

**Comment by mkocus** [comment]
A few questions:
1. When you enter the resource history on the web UI for this resource, do you see the input, outputs and metadata of the commit, which should trigger the build?
2. Have you set up the `version: every` and `trigger: true` in the pipeline for that resource? Like that:
```
  - get: pull-request
    trigger: true
    version: every
```

We are using that resource in couple of our pipelines and it generally works.

**Comment by kardashov** [comment]
Hmm. Starting from today it works as expected. Seems that source of the problem with PR was on Bitbucket.org side: 
https://community.atlassian.com/t5/Bitbucket-articles/Extinguishing-our-performance-fires-and-rebuilding-for-the/ba-p/1679820#M1048
Thank you @mkocus.
