### ISSUE TITLE
Add paths and ignore_paths like in concourse/git-resources

### ISSUE THREAD

**Issue by kairat1115** [n7mobile/concourse-bitbucket-pr#6]
Would like to see option for `paths` and `ignore_paths` like in https://github.com/concourse/git-resource#source-configuration

- paths: Optional. If specified (as a list of glob patterns), only changes to the specified files will yield new versions from check.
- ignore_paths: Optional. The inverse of paths; changes to the specified files are ignored.

**Comment by antrov** [comment]
Hi @kairat1115 , thanks for sharing your idea. 

Unluckily, tracing of paths in repository would be contrary to basic concept of this resource. To be more specific: our goal is to minimize to the lowest possible level number of all interactions with the Bitbucket Services. Every interaction consumes limit of available requests pool. Every request over git protocol counts also. Fetching of the full repository on an every version check step will consume limits in no time.

Approach we would follow, is to ignore commits with special comment like [skip ci]. This is on the roadmap for following months.
